# Site settings
course_name: Embedded Systems Design and Modeling
course_description: "The Embedded Systems Design and Modeling course explores the principles and practices of designing systems that integrate computation with physical processes, known as cyber-physical systems (CPS). Rooted in the textbook Introduction to Embedded Systems: A Cyber-Physical Systems Approach by Lee and Seshia, this course shifts focus from traditional computing—where the emphasis is on information processing—to the unique challenges of embedded systems. These systems, which power devices like automotive controls, medical instruments, industrial robots, and smart appliances, require engineers to understand the joint dynamics of software, hardware, and physical environments."
course_semester: "Fall 2025"

baseurl: "/webpage" # the subpath of your site, e.g. /blog/
url: "http://ce5439-aut.github.io/webpage" # the base hostname & protocol for your site

schoolname: "Amirkabir University of Technology (Tehran Polytechnic)"
schoolurl: "https://ce.aut.ac.ir"
twitter_username: aut1928 

address: |
    Computer Engineering Department
    Amirkabir University of Technology
    Tehran, Iran

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
