# Site settings
course_name: Embedded Systems Modeling and Design
course_description: "The Embedded Systems Modeling and Design course explores the principles and practices of designing systems that integrate computation with physical processes, known as cyber-physical systems (CPS). Rooted in the textbook Introduction to Embedded Systems: A Cyber-Physical Systems Approach by Lee and Seshia, this course shifts focus from traditional computing—where the emphasis is on information processing—to the unique challenges of embedded systems. These systems, which power devices like automotive controls, medical instruments, industrial robots, and smart appliances, require engineers to understand the joint dynamics of software, hardware, and physical environments. Central to the course is the study of how embedded software interacts with real-world processes through feedback loops, where computational decisions directly affect physical outcomes and vice versa. Key topics include modeling concurrent behaviors, managing real-time constraints, and bridging the gap between sequential software semantics and the inherently parallel nature of physical systems. Students will learn to design systems where timing, concurrency, and reliability are critical to correctness, not just performance. Through hands-on projects and theoretical analysis, the course equips learners with tools to address challenges such as synchronization, resource allocation, and verification in safety-critical applications. By the end of the course, students will be prepared to engineer robust, efficient embedded systems that harmonize cyber and physical elements in a rapidly evolving technological landscape."
course_semester: "Fall 2025"

baseurl: "/Webpage" # the subpath of your site, e.g. /blog/
url: "http://ce5439-aut.github.io/webpage" # the base hostname & protocol for your site

schoolname: "Amirkabir University of Technology (Tehran Polytechnic)"
schoolurl: "https://ce.aut.ac.ir"
twitter_username: aut1928 

address: |
    Computer Engineering Department
    Amirkabir University of Technology
    Tehran, Iran

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
